// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCalendarGoal(arg1:string,arg2:number,arg3:string):Promise<Array<main.Goal>>;

export function AddCategory(arg1:string):Promise<Array<string>>;

export function AddGoal(arg1:string):Promise<Array<main.Goal>>;

export function DeleteBook(arg1:string):Promise<void>;

export function DeleteCategory(arg1:string):Promise<Array<string>>;

export function DeleteGoal(arg1:string):Promise<Array<main.Goal>>;

export function GetBook(arg1:string):Promise<main.Book>;

export function GetBooks():Promise<Array<main.Book>>;

export function GetCategories():Promise<Array<string>>;

export function GetGoals():Promise<Array<main.Goal>>;

export function SaveCoverData(arg1:string,arg2:string):Promise<void>;

export function SelectAndAddBook():Promise<main.Book>;

export function SetBookCategory(arg1:string,arg2:string):Promise<void>;

export function ToggleGoal(arg1:string):Promise<Array<main.Goal>>;

export function Translate(arg1:string,arg2:string):Promise<string>;

export function UpdateGoal(arg1:string,arg2:string):Promise<Array<main.Goal>>;

export function UpdateGoalDayTime(arg1:string,arg2:number,arg3:string):Promise<Array<main.Goal>>;

export function UpdateProgress(arg1:string,arg2:number,arg3:number):Promise<void>;
