// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCategory(arg1) {
  return window['go']['main']['App']['AddCategory'](arg1);
}

export function DeleteBook(arg1) {
  return window['go']['main']['App']['DeleteBook'](arg1);
}

export function DeleteCategory(arg1) {
  return window['go']['main']['App']['DeleteCategory'](arg1);
}

export function GetBook(arg1) {
  return window['go']['main']['App']['GetBook'](arg1);
}

export function GetBooks() {
  return window['go']['main']['App']['GetBooks']();
}

export function GetCategories() {
  return window['go']['main']['App']['GetCategories']();
}

export function SaveCoverData(arg1, arg2) {
  return window['go']['main']['App']['SaveCoverData'](arg1, arg2);
}

export function SelectAndAddBook() {
  return window['go']['main']['App']['SelectAndAddBook']();
}

export function SetBookCategory(arg1, arg2) {
  return window['go']['main']['App']['SetBookCategory'](arg1, arg2);
}

export function Translate(arg1, arg2) {
  return window['go']['main']['App']['Translate'](arg1, arg2);
}

export function UpdateProgress(arg1, arg2, arg3) {
  return window['go']['main']['App']['UpdateProgress'](arg1, arg2, arg3);
}
